name: 构建

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean
  push:
    branches:
      - master
    paths:
      - "docker/**"
      - "**.sh"
      - "**.json"

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          #  两行一组，删除不需要的版本
          - platform: ds918p
            version: 7.0.1-42218
          - platform: ds918p
            version: 7.1.0-42661
    steps:
      - name: 测试变量输出
        if: "${{ github.event.inputs.clean_cache == 'true' }}"
        run: |
          echo ${{secrets.TEST_ENV}}
      
